# Generated by Django 3.2.16 on 2022-11-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='width',
            new_name='weight',
        ),
    ]
