# Generated by Django 4.1.3 on 2022-11-09 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_rename_firstname_person_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('string_no', models.CharField(choices=[('First String', 'First String'), ('Second String', 'Second String')], max_length=100)),
                ('isActive', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player', to='baseball.person')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='baseball.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
