# Generated by Django 3.2.16 on 2022-11-26 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='baseball.club'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_t1', models.IntegerField()),
                ('score_t2', models.IntegerField()),
                ('game_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date of Issuance')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1', to='baseball.club')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2', to='baseball.club')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to='baseball.club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
